<?php

$skills = [
  ['id' => '1', 'name' => 'C++', 'description' => ''],
  ['id' => '2', 'name' => 'Python', 'description' => ''],
  ['id' => '3', 'name' => 'Java', 'description' => ''],
  ['id' => '4', 'name' => 'C#', 'description' => ''],
  ['id' => '5', 'name' => 'PHP', 'description' => ''],
  ['id' => '6', 'name' => 'MySQL', 'description' => ''],
  ['id' => '7', 'name' => 'JavaScript', 'description' => ''],
  ['id' => '8', 'name' => 'CSS', 'description' => ''],
  ['id' => '9', 'name' => 'HTML', 'description' => ''],
  ['id' => '10', 'name' => 'Accountant', 'description' => ''],
  ['id' => '11', 'name' => 'Vue', 'description' => ''],
  ['id' => '12', 'name' => 'ReactJS', 'description' => ''],
  ['id' => '13', 'name' => 'jQuery', 'description' => ''],
  ['id' => '14', 'name' => 'AJAX', 'description' => ''],
  ['id' => '15', 'name' => 'JSON', 'description' => ''],
  ['id' => '16', 'name' => 'Linux', 'description' => ''],
  ['id' => '17', 'name' => 'AngularJS', 'description' => ''],
  ['id' => '18', 'name' => 'Electron', 'description' => ''],
  ['id' => '19', 'name' => 'Amber', 'description' => ''],
  ['id' => '20', 'name' => 'Ruby', 'description' => ''],
  ['id' => '21', 'name' => 'Django', 'description' => ''],
  ['id' => '22', 'name' => 'Laravel', 'description' => ''],
  ['id' => '23', 'name' => 'Code Igniter', 'description' => ''],
  ['id' => '24', 'name' => 'Cake PHP', 'description' => ''],
  ['id' => '25', 'name' => 'Wordpress', 'description' => ''],
  ['id' => '26', 'name' => 'YII', 'description' => ''],
  ['id' => '27', 'name' => 'Magento', 'description' => ''],
  ['id' => '28', 'name' => 'Shopify', 'description' => ''],
  ['id' => '29', 'name' => 'Analytical', 'description' => 'Analytical'],
  ['id' => '30', 'name' => 'Conceptual', 'description' => NULL],
  ['id' => '32', 'name' => 'Programming', 'description' => NULL],
  ['id' => '33', 'name' => 'RMI', 'description' => NULL],
  ['id' => '34', 'name' => 'XML', 'description' => NULL],
  ['id' => '35', 'name' => 'UNIX', 'description' => NULL]
];
